### ISSUE TITLE
Running the example

### ISSUE THREAD

**Issue by tworitdash** [monami-ya-mrb/mruby-serialport#1]
I am pretty new to mruby. I want to run a serialport program from my raspberry pi to a ARM Cortex M4, which has been programmed to perform some tasks upon some instructions. I want to provide the instructions from a mruby program. My build_config.rb looks like this. 

``` ruby
############################
# Start of your build_config

MRuby::Build.new do |conf|
  toolchain :gcc

  conf.bins = %w(mrbc)

  # mruby's Core GEMs
  conf.gem 'mrbgems/mruby-bin-mirb'
  conf.gem 'mrbgems/mruby-bin-mruby'
  conf.gem 'mrbgems/mruby-array-ext'
  conf.gem 'mrbgems/mruby-enum-ext'
  conf.gem 'mrbgems/mruby-eval'
  conf.gem 'mrbgems/mruby-exit'
  conf.gem 'mrbgems/mruby-fiber'
  conf.gem 'mrbgems/mruby-hash-ext'
  conf.gem 'mrbgems/mruby-math'
  conf.gem 'mrbgems/mruby-numeric-ext'
  conf.gem 'mrbgems/mruby-object-ext'
  conf.gem 'mrbgems/mruby-objectspace'
  conf.gem 'mrbgems/mruby-print'
  conf.gem 'mrbgems/mruby-proc-ext'
  conf.gem 'mrbgems/mruby-random'
  conf.gem 'mrbgems/mruby-range-ext'
  conf.gem 'mrbgems/mruby-sprintf'
  conf.gem 'mrbgems/mruby-string-ext'
#  conf.gem 'mrbgems/mruby-string-utf8'
  conf.gem 'mrbgems/mruby-struct'
  conf.gem 'mrbgems/mruby-symbol-ext'
  conf.gem 'mrbgems/mruby-time'
  conf.gem 'mrbgems/mruby-toplevel-ext'

  # user-defined GEMs
  conf.gem :git => 'https://github.com/monami-ya-mrb/mruby-serialport.git'
end

# End of your build_config
############################
```

Then I aaded unistd.h and string.h in serport-impl-posix.c in mruby/build/mrbgems/mruby-serialport/src to avoid some errors of undefined function declarations. Then I did this 
    sudo rake
And it was successfully built. 
Now I see a serialport.rb file in the test directory of the gem which is similar to what I write in ruby for serialport programming. Hence, I changed it a bit to write some characters to the serialport where my ARM Controller has been connected. My serialport.rb looks like this.

``` ruby
assert("serial") do
  sp = SerialPort.new("/dev/ttyACM0", 115200, 8, 1, 0)
  sp.read_timeout=1000
  wait_time = 4
  sp.puts "foobarbaz"
  sp.gets == "foobarbaz\n"
  list = ["f", "l", "r", "b", "s"]
  list.each do |l|
    sp.write(l)
    sleep wait_time
  end
end
```

After this when I read about the five ways to run a mruby program and tried the first one with mruby compiler for running pure ruby code like "mruby serialport.rb" , I get the error like this 

```
    [0] ../test/serialport.rb:1
../test/serialport.rb:1: undefined method 'assert' for main (NoMethodError)
```

I have been following so many forums for this. If anybody please explain me how can I achieve this, I will be obliged. :smiley:

**Comment by monaka** [comment]
Hello. I don't touch recent versions of mruby. So this mrbgem may be pretty obsolete.
I'll try to update it but I'm busy this weekend and next week.
Please stay tune until next weekend. Of course your fix/pull request is welcome.

**Comment by tworitdash** [comment]
I will try of course. And I am eagerly waiting for next week. Thanks a lot. :smiley:

**Comment by kyab** [comment]
assert method is defined only for mruby's test infrastructure (with ./minirake test) so not defined in regular mruby binary.

Try with removing assert("..") line and check what happen.

``` ruby
#assert("serial") do
  sp = SerialPort.new("/dev/ttyACM0", 115200, 8, 1, 0)
  sp.read_timeout=1000
  wait_time = 4
  sp.puts "foobarbaz"
  sp.gets == "foobarbaz\n"
  list = ["f", "l", "r", "b", "s"]
  list.each do |l|
    sp.write(l)
    sleep wait_time
  end
#end
```

**Comment by tworitdash** [comment]
I got this.

```
mruby serialport.rb
```

```
trace:
    [0] serialport.rb:2
serialport.rb:2: illegal access mode rw (ArgumentError)
```

I don't know what it is but I can see a line of code in the mrblib/serialport.rb as the following.

``` ruby
def initialize(port, *params)
    fileno = create_port(port)
   super(fileno, "rw");

    begin
      set_modem_params(*params)
    rescue
      close
      raise
    end
  end
```

in the class SerialPort 
But I guess it should accept those 4 arguments. But what is this error I can't figure out. Please help.

**Comment by kyab** [comment]
Modify build/mrbgems/mruby-serialport/mrblib/serialport.rb as below and re-try.

``` ruby
  def initialize(port, *params)
    fileno = create_port(port)
    super(fileno, "r+");

    begin
      set_modem_params(*params)
    rescue
      close
      raise
    end
  end
```

**Comment by tworitdash** [comment]
The same error has come again, even after changing "rw" to "r+".

**Comment by tworitdash** [comment]
@kyab My bad ! Sorry I didn't build it again. Now everything works fine. Thanks a lot. :smiley: . By the way, the sleep function doesn't work as I guess the function is for ruby only, not for mruby. Can you please suggest me what to use if I need a delay during consecutive writes.

**Comment by kyab** [comment]
mruby-sleep may help you.
https://github.com/matsumoto-r/mruby-sleep

**Comment by tworitdash** [comment]
Thanks a lot. :smiley: . It's fun working.

**Comment by monaka** [comment]
I'm back... and the issue was resolved. Thanks @kyab -san so much! :sushi:
I'll patch it and close this issue soon.

**Comment by kyab** [comment]
Thanks for fix it.

**Comment by tworitdash** [comment]
Cool. Thanks a lot. :D
